source 'https://api.berkshelf.com'

cookbook 'apache2'
cookbook 'application'
cookbook 'application_php'
cookbook 'composer', git: 'https://github.com/Morphodo/chef-composer.git'
cookbook 'database'
cookbook 'jenkins'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'node'
cookbook 'nodejs'
cookbook 'php'
cookbook 'postgresql'
# cookbook 'boilerplate', path: '../topaz2/cookbooks/boilerplate'
# cookbook 'boilerplate_php', path: '../topaz2/cookbooks/boilerplate_php'
# cookbook 'netcommons', path: '../chef_netcommons'
cookbook 'boilerplate', git: 'https://github.com/topaz2/chef_boilerplate.git'
cookbook 'boilerplate_php', git: 'https://github.com/topaz2/chef_boilerplate_php.git'
cookbook 'netcommons', git: 'https://github.com/NetCommons3/chef_netcommons.git'
