source "https://rubygems.org"

gem 'activesupport'
gem 'bundler'
gem 'berkshelf'
gem 'nokogiri'
gem 'rake'
gem 'mysql'
gem 'gemrat'
gem 'chef'
gem 'i18n'

group :development, :test do
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-jasmine'
  gem 'guard-jshint-node'
  gem 'guard-kitchen'
  gem 'guard-livereload'
  gem 'guard-shell'
  gem 'jasmine'
  gem 'juicer'
  gem 'kitchen-vagrant'
  gem 'libnotify'
  gem 'rcodetools'
  gem 'ruby-prof'
  gem 'test-kitchen'
  gem 'jekyll'
  gem 'travis'
  gem 'travis-lint'
  gem 'knife-solo'
end
