source "https://rubygems.org"

gem 'activesupport'
gem 'bundler'
gem 'berkshelf'
gem 'nokogiri'
gem 'rake'
gem 'mysql'
gem 'pg'

group :development, :test do
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-jshint-node'
  gem 'guard-kitchen'
  gem 'guard-livereload'
  gem 'guard-phpcs'
  gem 'guard-phpmd'
  gem 'guard-phpunit2'
  gem 'guard-shell'
  gem 'juicer'
  gem 'kitchen-vagrant'
  gem 'libnotify'
  gem 'rcodetools'
  gem 'ruby-prof'
  gem 'test-kitchen'
  gem 'jekyll'
  gem 'travis'
  gem 'travis-lint'
end
