#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`

echo "Checking PHP Lint..."
FILES=""
for FILE in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\\\.\(php\|ctp\)\$`
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the parse error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done
FILES_CSV=`echo $FILES | sed 's/\s/,/g'`

if [ "$FILES" != "" ]
then
	echo "Running phpcs..."
	phpcs --extensions=php --standard=CakePHP --encoding=utf-8 $FILES
	if [ $? != 0 ]
	then
		echo "Fix the coding standard violations before commit."
		exit 1
	fi
fi

if [ "$FILES_CSV" != "" ]
then
	echo -n "Running phpmd..."
	phpmd $FILES_CSV text ruleset/phpmd.xml
	if [ $? != 0 ]
	then
		echo "Fix the coding standard violations before commit."
		exit 1
	fi
fi

if [ "$FILES" != "" ]
then
	echo "Running phpunit..."
	for TEST in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\Test\\.\(php\)\$ | sed 's/app\/Test\/Case\/\([a-zA-Z0-9\/]\+\)Test\.php/\1/g'`
	do
		./lib/Cake/Console/cake test app $TEST --stderr --configuration phpunit.xml.dist
		if [ $? != 0 ]
		then
			echo "Fix the test error before commit."
			exit 1
		fi
	done
fi

exit $?
